package com.yaji.traderev.carauction.enums;

public enum ErrorCode {
  AUCTIONS_NOT_FOUND,
  AUCTION_RESOURCE_NOT_FOUND,
  AUCTION_CLOSED,
  AUCTION_NOT_OPEN_YET,
  WINNING_BID_NOT_FOUND,
  BID_RESOURCE_NOT_FOUND,
  BIDS_NOT_FOUND,
  BID_LESSER_THANOR_EQUAL_TO_WINNING_BID,
  CAR_INFOS_NOT_FOUND,
  CAR_INFO_RESOURCE_NOT_FOUND,
  USER_INFOS_NOT_FOUND,
  USER_INFO_RESOURCE_NOT_FOUND,
  USERS_NOT_FOUND,
  USER_RESOURCE_NOT_FOUND,
  WRONG_AUCTION_TO_BID_MAPPING,
  CONFLICTING_AUCTION_IDS,
  OBJECT_COULD_NOT_BE_MODIFIED,
  WRONG_DTO_TO_ENTITY_MAPPING,
  INTERNAL_STATE_ERROR
}
