package com.yaji.traderev.carauction.enums;

public enum ErrorCode {
	AUCTIONS_NOT_FOUND,
  AUCTION_RESOURCE_NOT_FOUND,
  BID_RESOURCE_NOT_FOUND,
  BIDS_NOT_FOUND,
  CAR_INFOS_NOT_FOUND,
  CAR_INFO_RESOURCE_NOT_FOUND,
  WRONG_AUCTION_TO_BID_MAPPING,
  CONFLICTING_AUCTION_IDS,
  OBJECT_COULD_NOT_BE_MODIFIED,
  WRONG_DTO_TO_ENTITY_MAPPING
}
